# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Travvora

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_577572ebaeb7473581c21dd84d6bc679 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7c570fd8474045d99a41fa65ea4c26f7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_577572ebaeb7473581c21dd84d6bc679 }}/travvorahms:${{ github.sha }}
        file: ./php/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Travvora'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_dc2d5735dbd445b9af24374f312683f1 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_577572ebaeb7473581c21dd84d6bc679 }}/travvorahms:${{ github.sha }}'
