# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Travvora

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d5027c8c6c8e42f0a8559258cf43deaf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c49a89bc220f40a3b159963ac8226a42 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d5027c8c6c8e42f0a8559258cf43deaf }}/travvorahms:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Travvora'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_55e5c3a2ff7e4b3680875422b517463c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d5027c8c6c8e42f0a8559258cf43deaf }}/travvorahms:${{ github.sha }}'